1. Generate two  3 x 3 matrix and find it's dot product and take the transpose of the answer.

In [19]:
#please provide your answer below this line.
import numpy as np 

x = np.arange(0,9).reshape(3,3)
print(x) 

y = np.arange(1,10).reshape(3,3) 
print(y) 

z = np.dot(x,y) 
print(z) 

w = z.T
print(w)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 18  21  24]
 [ 54  66  78]
 [ 90 111 132]]
[[ 18  54  90]
 [ 21  66 111]
 [ 24  78 132]]


2. Create a 3x3 matrix with elements [55,25,15], [30,44,2], [11,45,77] . Now find the determinant of the given matrix.

In [18]:
#please provide your answer below this line.
import numpy as np 

n_array = np.array([[55, 25, 15], 
                    [30, 44, 2], 
                    [11, 45, 77]]) 

 
print("Numpy Matrix is:") 

print(n_array) 

   
det = np.linalg.det(n_array) 

     
print("\nDeterminant of given 3X3 square matrix:") 

print(int(det))

Numpy Matrix is:
[[55 25 15]
 [30 44  2]
 [11 45 77]]

Determinant of given 3X3 square matrix:
137180
