1. Create a DataFrame by passing a random numpy array,with a datetie index and labelled columns.and display its,
     - Head
     - Tail
     - Index 
     - Columns
     - Values
     - statistics


In [4]:
#please type your answer below this line.
import numpy as np
import pandas as pd
datetie = pd.date_range('2021-08-30' ,periods=4)
df = pd.DataFrame(np.random.randn(4,4), index=datetie, columns=list('ABCD'))
print("Head:\n", df.head())
print("Tail:\n", df.tail())
print("Index:\n", df.index)
print("Columns:\n", df.columns)
print("Values:\n", df.values)
print("Statistics:\n", df.describe(include='all'))

Head:
                    A         B         C         D
2021-08-30  0.864937  1.347978  0.506583 -0.171222
2021-08-31  0.665431 -0.899810 -0.018916 -1.549593
2021-09-01 -1.254894 -0.499196 -1.000246 -1.244260
2021-09-02 -0.441530 -0.019370 -0.942566 -1.471744
Tail:
                    A         B         C         D
2021-08-30  0.864937  1.347978  0.506583 -0.171222
2021-08-31  0.665431 -0.899810 -0.018916 -1.549593
2021-09-01 -1.254894 -0.499196 -1.000246 -1.244260
2021-09-02 -0.441530 -0.019370 -0.942566 -1.471744
Index:
 DatetimeIndex(['2021-08-30', '2021-08-31', '2021-09-01', '2021-09-02'], dtype='datetime64[ns]', freq='D')
Columns:
 Index(['A', 'B', 'C', 'D'], dtype='object')
Values:
 [[ 0.86493727  1.34797811  0.5065831  -0.17122174]
 [ 0.66543109 -0.89981004 -0.01891565 -1.54959298]
 [-1.25489395 -0.4991964  -1.00024621 -1.24425966]
 [-0.44153032 -0.01936954 -0.94256552 -1.47174373]]
Statistics:
               A         B         C         D
count  4.000000  4.000000  4.000000

2. Use the above table and,
      - find transpose of your data.
      - sort the index in the descending order of the date.

In [3]:
#please provide your answer below this line.
print("Transpose\n" , df.transpose())
print("Sorted in Descending Order\n" , df.sort_index(ascending=False))

Transpose
    2021-08-30  2021-08-31  2021-09-01  2021-09-02
A   -0.722003   -0.538166    0.622751    0.225840
B    0.634784   -0.778754    0.604609   -1.929643
C   -1.378001   -0.413602   -1.618353    0.658484
D   -0.395848   -0.251114   -2.429237    0.145666
Sorted in Descending Order
                    A         B         C         D
2021-09-02  0.225840 -1.929643  0.658484  0.145666
2021-09-01  0.622751  0.604609 -1.618353 -2.429237
2021-08-31 -0.538166 -0.778754 -0.413602 -0.251114
2021-08-30 -0.722003  0.634784 -1.378001 -0.395848
