1. Create a 3x3 array values ranging from 0-8.Find the sum of the elements in this array.

In [17]:
#please enter your code below this line.
import numpy as np
x = np.arange(0,9).reshape(3,3)
y = np.sum(x)
print('Sum of the array is ', y)

Sum of the array is  36


2. Create a 3x3 array values ranging from 0-8.Find the row sum and column sum of this array.

In [18]:
#please enter your code below this line.
import numpy as np
x = np.arange(0,9).reshape(3,3)
print("sum1, 2, 3: ", x.sum(axis = 1))
print("sum1, 2, 3: ", x.sum(axis = 0))

sum1, 2, 3:  [ 3 12 21]
sum1, 2, 3:  [ 9 12 15]


3. Create a 4x4 array values ranging from 0-15. Now,

    a) Find the mininmum value in the array.
    
    b) Find the maximum value in the array.

    c) Find the mean of the values in the array.

In [19]:
#please enter your code belowthis line.
import numpy as np
x = np.arange(0,16).reshape(4,4)
y = np.min(x)
z = np.max(x)
w = np.mean(x)
print(y)
print(z)
print(w)

0
15
7.5


4. Create an 10x10 array values ranging from 0-99.And ,

    a) Print the 7th row.
    
    b) Print the rows from 4-8.

    c) Print the value at the index 5,5.

    d) Print the 5th colomn.

    e) Print the columns from 2-5.

In [16]:
#please enter your code below this line.
import numpy as np
x = np.arange(0,100).reshape (10,10)
print(x)

print("Seventh Row")
print(x[7])

print("Rows from 4-8")
print(x[4:9])

print("Value at the Index 5,5")
print(x[5,5])

print("5th column")
print(x[0:10,5])

print("Columns from 2-5")
print(x[0:10,2:6])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
Seventh Row
[70 71 72 73 74 75 76 77 78 79]
Rows from 4-8
[[40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]]
Value at the Index 5,5
55
5th column
[ 5 15 25 35 45 55 65 75 85 95]
Columns from 2-5
[[ 2  3  4  5]
 [12 13 14 15]
 [22 23 24 25]
 [32 33 34 35]
 [42 43 44 45]
 [52 53 54 55]
 [62 63 64 65]
 [72 73 74 75]
 [82 83 84 85]
 [92 93 94 95]]
