1. Create an 4x4 array with elements ranging from 0-15. And find the trace of the array.

In [19]:
#please type your answer below this line.
import numpy as np 

x = np.arange(0,16).reshape(4,4) 
print(x)

y = np.trace(x)
print("Trace of the matrix is =", y) 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Trace of the matrix is = 30


2. Create a matrix with elements [6,1,1],[4,-2,5],[2,8,7].Now find the inverse this matrix.

In [14]:
#please type your answer below this line.
import numpy as np

x = np.array([[6,1,1],[4,-2,5],[2,8,7]])
print(x) 

print("The inverse of the matrix is =") 
y = np.linalg.inv(x)
print(y)

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
The inverse of the matrix is =
[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


3. Create an 3x3 array with elements ranging from 0-8. And find the norm this array.

In [15]:
#please type your answer below this line.
import numpy as np

x = np.arange(0,9).reshape(3,3) 
print(x) 

x_norm = np.linalg.norm(x)

print("Matrix norm:")

print(x_norm)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
Matrix norm:
14.2828568570857


4. Create a 4x4 array whose value ranging from 0-15.And find the eigenvalues and eigenvectors of this array.

In [ ]:
#please type your answer below this line.
import numpy as np
from numpy.linalg import eig
a = np.arange(0,16).reshape(4,4) 

w,v=eig(a)
print('E-value:', w)
print('E-vector:', v)