1. Generate a 3 x 3 matrix using random module.

In [1]:
#please provide your answer below this line.
import numpy as np
x =  np.arange(2, 11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [2]:
#please provide your answer below this line.
import numpy as np
x =  np.arange(2, 18).reshape(4,4)
print(x)

y =  np.arange(19,35).reshape(4,4)
print(y)

x = np.arange(2, 18).reshape(2,8) 
print(x)

y = np.arange(19,35).reshape(2,8)
print(y)

z = np.vstack((x,y)) 
print(z)

w = np.hstack((x, y)) 
print(w)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]]
[[19 20 21 22]
 [23 24 25 26]
 [27 28 29 30]
 [31 32 33 34]]
[[ 2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17]]
[[19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34]]
[[ 2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17]
 [19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34]]
[[ 2  3  4  5  6  7  8  9 19 20 21 22 23 24 25 26]
 [10 11 12 13 14 15 16 17 27 28 29 30 31 32 33 34]]
